GET http://localhost:3000/api/posts

###
GET http://localhost:3000/api/posts/1

###
GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/1

###
GET http://localhost:3000/api/user/Lodjuret2001

###
POST http://localhost:3000/api/login
//Mock user
Content-Type: application/json
{
"username": "Lodjuret2001",
"password": "SuccsessPassword"
}