### Protected Path
GET http://localhost:3000/api/posts/user

### Protected Path
GET http://localhost:3000/api/post/4

### Protected path
GET http://localhost:3000/api/user/1

###
POST http://localhost:4000/api/login
Content-Type: application/json

{
    "username": "Lodjuret2001",
    "password": "SuccsessPassword"
}

###
DELETE http://localhost:4000/api/logout